services:
    _defaults:
        autowire: true
        autoconfigure: true

    OHMedia\PhotoBundle\:
        resource: '../src/'
        exclude:
            - '../src/Entity/'
            - '../src/OHMediaPhotoBundle.php'
